version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
